#!/bin/sh
echo 'Running ICNS checkpoint restart test'
echo '===================================='
if [ ! -d "iter_1" ]; then
    echo "*** Output directory not created" 1>&2
    exit 1
fi
mpirun -np 4 ./cylinder -p parameters -c iter_1/primal0 -i 1
