#!/bin/sh
cd icns
echo 'Running ICNS solver test'
echo '========================'
rm -fr iter*
if which mpirun >/dev/null; then
    mpirun -np 4 ./cylinder -p parameters -m ../../ucsolver/icns/cylinder/cylinder_3d_bmk.xml.gz
else
    mpiexec -np 4 ./cylinder -p parameters -m ../../ucsolver/icns/cylinder/cylinder_3d_bmk.xml.gz
fi